# Generated by Django 4.1.2 on 2023-11-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Isotope',
            fields=[
                ('isotope_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('isotope_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id1', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id1', models.CharField(max_length=30)),
                ('isotope_level', models.FloatField()),
                ('isotope_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.isotope')),
            ],
        ),
    ]
