# Generated by Django 4.1.2 on 2023-11-19 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='job_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.customer'),
        ),
    ]
