# Generated by Django 5.0.1 on 2024-01-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_alter_activity_job_id1_alter_job_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=30)),
                ('criteria_type', models.CharField(choices=[('RANGE', 'range'), ('EXACT NUMBER', 'exact number'), ('EXACT TEXT', 'exact text'), ('MINIMUM', 'minimum'), ('MAXIMUM', 'maximum')], max_length=30)),
                ('condition_type', models.CharField(choices=[('NONE', 'none'), ('NUMBER', 'number'), ('TEXT', 'text')], max_length=30)),
                ('range_min', models.FloatField()),
                ('range_max', models.FloatField()),
                ('exact_criteria', models.FloatField()),
                ('exact_text', models.CharField(max_length=30)),
                ('min_minimum', models.FloatField()),
                ('max_maximum', models.FloatField()),
                ('parameter_number', models.CharField(max_length=30)),
                ('greater_than', models.FloatField()),
                ('greater_than_or_equal_to', models.FloatField()),
                ('less_than', models.FloatField()),
                ('less_than_or_equal_to', models.FloatField()),
                ('parameter_text', models.CharField(max_length=30)),
                ('parameter_is', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('dimension', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Test',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='isotope_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='job_id1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='customer_name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='customer_name',
            new_name='test',
        ),
        migrations.DeleteModel(
            name='Isotope',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
